# =============================================================================
# Flight Booking — Ansible Inventory
# be-flight-booking/infrastructure/ansible/inventory.ini
# =============================================================================

[staging]
staging.yourdomain.com ansible_host=YOUR_STAGING_IP ansible_user=root

[production]
prod.yourdomain.com ansible_host=YOUR_PROD_IP ansible_user=root

[monitoring]
monitoring.yourdomain.com ansible_host=YOUR_MONITORING_IP ansible_user=root

[flight-booking:children]
staging
production
monitoring

[flight-booking:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
