/**
 * Script để verify và update image_url cho deals
 * 
 * Usage:
 *   npx ts-node scripts/verify-deals-images.ts
 * 
 * Hoặc với tsx:
 *   npx tsx scripts/verify-deals-images.ts
 */

import { readdir, stat } from 'fs/promises';
import { join } from 'path';
import { existsSync } from 'fs';

const PUBLIC_IMAGES_ROUTES = join(process.cwd(), 'public', 'images', 'routes');

interface ImageInfo {
	filename: string;
	routeId: string;
	exists: boolean;
	size?: number;
}

/**
 * Lấy danh sách tất cả file ảnh trong public/images/routes/
 */
async function getImageFiles(): Promise<ImageInfo[]> {
	if (!existsSync(PUBLIC_IMAGES_ROUTES)) {
		console.log('Thư mục public/images/routes/ không tồn tại!');
		return [];
	}

	const files = await readdir(PUBLIC_IMAGES_ROUTES);
	const images: ImageInfo[] = [];

	for (const file of files) {
		if (!file.endsWith('.jpg') && !file.endsWith('.jpeg')) {
			continue;
		}

		// Extract route_id từ filename (bỏ extension)
		const routeId = file.replace(/\.(jpg|jpeg)$/i, '');
		
		// Validate UUID format (36 characters với dashes)
		const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
		if (!uuidRegex.test(routeId)) {
			console.warn(`File không đúng format UUID: ${file}`);
			continue;
		}

		const filePath = join(PUBLIC_IMAGES_ROUTES, file);
		const stats = await stat(filePath);

		images.push({
			filename: file,
			routeId,
			exists: true,
			size: stats.size,
		});
	}

	return images;
}

/**
 * Generate SQL script để update image_url
 */
function generateUpdateSQL(routeIds: string[]): string {
	if (routeIds.length === 0) {
		return '-- Không có route nào cần update';
	}

	const updates = routeIds.map(routeId => {
		const imageUrl = `/images/routes/${routeId}.jpg`;
		return `UPDATE Routes SET image_url = '${imageUrl}' WHERE route_id = '${routeId}';`;
	});

	return `-- =========================================================
-- UPDATE IMAGE_URL CHO ${routeIds.length} ROUTES
-- =========================================================
-- Generated by: scripts/verify-deals-images.ts
-- Date: ${new Date().toISOString()}
-- =========================================================

USE flight_booking_db;
GO

${updates.join('\n')}

GO

-- Verify
SELECT 
    r.route_id,
    o.iata_code AS origin,
    d.iata_code AS destination,
    r.image_url
FROM Routes r
INNER JOIN Airports o ON r.origin_airport_id = o.airport_id
INNER JOIN Airports d ON r.destination_airport_id = d.airport_id
WHERE r.route_id IN (${routeIds.map(id => `'${id}'`).join(', ')})
ORDER BY o.iata_code, d.iata_code;
GO
`;
}

/**
 * Main function
 */
async function main() {
	console.log('Đang kiểm tra ảnh deals...\n');

	const images = await getImageFiles();

	if (images.length === 0) {
		console.log('Không tìm thấy file ảnh nào trong public/images/routes/');
		console.log('\nHướng dẫn:');
		console.log('   1. Đặt các file ảnh vào: public/images/routes/');
		console.log('   2. Đặt tên file theo format: {route_id}.jpg');
		console.log('   3. route_id là UUID v7 (36 ký tự)');
		return;
	}

	console.log(`Tìm thấy ${images.length} file ảnh:\n`);

	// Hiển thị thông tin từng file
	let totalSize = 0;
	for (const img of images) {
		const sizeMB = img.size ? (img.size / 1024 / 1024).toFixed(2) : '?';
		totalSize += img.size || 0;
		console.log(`   ${img.filename}`);
		console.log(`      Route ID: ${img.routeId}`);
		console.log(`      Size: ${sizeMB} MB`);
		console.log(`      URL: /images/routes/${img.filename}`);
		console.log('');
	}

	const totalSizeMB = (totalSize / 1024 / 1024).toFixed(2);
	console.log(`Tổng kết:`);
	console.log(`   - Số lượng ảnh: ${images.length}`);
	console.log(`   - Tổng dung lượng: ${totalSizeMB} MB`);
	console.log('');

	// Generate SQL script
	const routeIds = images.map(img => img.routeId);
	const sqlScript = generateUpdateSQL(routeIds);

	const sqlFilePath = join(process.cwd(), 'sql', 'utils', 'update-deals-images-urls.sql');
	
	// Note: Không tự động write file, chỉ hiển thị
	console.log('SQL Script để update image_url:\n');
	console.log('─'.repeat(60));
	console.log(sqlScript);
	console.log('─'.repeat(60));
	console.log('');
	console.log(`Lưu ý: Script trên đã được generate, bạn có thể copy và chạy trong SQL Server.`);
	console.log(`   Hoặc lưu vào file: ${sqlFilePath}`);
	console.log('');
	console.log('Hoàn tất!');
}

// Run script
main().catch((error) => {
	console.error('Lỗi:', error);
	process.exit(1);
});

